[build]
  publish = "."
  command = "echo 'No build step required'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Fixed redirect rule - removed admin condition
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle specific file extensions that should not redirect
[[redirects]]
  from = "/*.js"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.css"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.png"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.jpg"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.jpeg"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.gif"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.svg"
  to = "/:splat"
  status = 200